### ISSUE TITLE
Protocol version is not the same as Node version

### ISSUE THREAD

**Issue by CathalT** [BitDesert/MyNanoNinja#16]
https://github.com/BitDesert/MyNanoNinja/blob/65165597a358a2d4692a3d1fa4a7df3256b79196/nano/protomap.js#L19

Both Node V19.0 and V20.0 are on protocol version 17 I believe, unfortunately I don't know if its possible to find out a node's version just from the peer_details.

**Comment by BitDesert** [comment]
That could improve with node telemetry, but for now it's not possible to know the exact node version from the protocol version (unfortunately).

**Comment by BitDesert** [comment]
Node telemetry is now set up.
