### ISSUE TITLE
Secret session key in public repo

### ISSUE THREAD

**Issue by pRizz** [BitDesert/MyNanoNinja#2]
Seems like a potential issue

https://github.com/BitDesert/MyNanoNinja/blob/master/app.js#L50

Maybe pass it in as an environment var

**Comment by BitDesert** [comment]
Yeah it's a placeholder, but it's probably better as a environment variable. Thanks! 
Fixed with 6a1a2fe25e15ca2d2f1dba6def836a2cd40b7db0
