### ISSUE TITLE
Node is V21 but displayed as V20

### ISSUE THREAD

**Issue by Falsen** [BitDesert/MyNanoNinja#22]
Our node has been upgraded to V21, but according to MyNanoNinja it is still V20.

Node monitor: http://167.71.245.153/
MyNanoNinja page: https://mynano.ninja/account/upstart-hosting

On NanoCrawler it is also displayed as V21: https://nanocrawler.cc/network (scroll down).

**Comment by BitDesert** [comment]
I switched the method how I get the node version to the telemetry it sends. This is way more reliable.
Unfortunately I don't get any data from your node. Mostly because of https://github.com/nanocurrency/nano-node/issues/2176
