### ISSUE TITLE
Google OAuth is broken.

### ISSUE THREAD

**Issue by n1ghtshade** [BitDesert/MyNanoNinja#3]
When trying to login at https://mynano.ninja/auth/login 
and choosing google, it's no longer possible to login with google.
Error: client_secret is missing.
![capture](https://user-images.githubusercontent.com/38169527/46626720-cc6c8200-cafd-11e8-93da-c82745ad95b2.PNG)

(This also happened when I was configuring the OAuth on my own hosted copy)

**Comment by BitDesert** [comment]
In the meantime the Google Login got removed.
