### ISSUE TITLE
Incorrect server providers data

### ISSUE THREAD

**Issue by n1ghtshade** [BitDesert/MyNanoNinja#4]
My hosting provider is netcup, but my nodes show with incorrect hosting providers on the ninja.

(I don't use cloudflare)

![screenshot_20181110-191449_chrome](https://user-images.githubusercontent.com/38169527/48315124-8c327080-e58f-11e8-9f6e-160406146941.jpg)
![screenshot_20181110-191439_chrome](https://user-images.githubusercontent.com/38169527/48315126-905e8e00-e58f-11e8-84bc-500d33746a8e.jpg)
![screenshot_20181110-191430_chrome](https://user-images.githubusercontent.com/38169527/48315128-95bbd880-e58f-11e8-848c-55df54a75ef0.jpg)

**Comment by BitDesert** [comment]
It depends on the IP from where I got the first vote from. If that's wrong you can PM me the correct IP of your node and I will fix it.
