### ISSUE TITLE
Cannot change or clear node monitor URL

### ISSUE THREAD

**Issue by kbailey204** [BitDesert/MyNanoNinja#48]
I'm trying to clear or change my node monitor URL. The old URL that does not work anymore is http, not https.

https://mynano.ninja/account/nano_3i3dqy5xs98ewtk9ejfpxfwbsscejc6njz9hk5ia1446gdkxpxkjeeia719n

**Comment by humble-nano** [comment]
i have the same issue, and i can't leave it blank @BitDesert
