### ISSUE TITLE
Please also show the profiles of verified nodes that aren't representatives

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [BitDesert/MyNanoNinja#8]
All that data, _Introduction, Website, etc._, seems to only be displayed for representatives. That isn't fair, it should be displayed for all the nodes that paid 1 NANO to become verified, and might become representatives in the future.

**Comment by BitDesert** [comment]
But that's already the case? For example: https://mynano.ninja/account/xrb_1e6e41up4x5e4jke6wy4k6nnuagagspfx4tjafghub6cw46ueimqt657nx4a

**Comment by Laurentiu-Andronache** [comment]
Here's a random example of an account that doesn't have the info showing: https://mynano.ninja/account/xrb_1ahgjp3nd4sx6q8nc7f753dnr6n43o8hkooce3pqqn877b6brj8ec5g5iagt

**Comment by BitDesert** [comment]
Ah now I get it... Sure thing, will change that.

**Comment by BitDesert** [comment]
Fixed with https://github.com/BitDesert/MyNanoNinja/commit/0e4070835a0c5b3a75b8afdf5e40661a5653cd37
